// <auto-generated />
using System;
using MauiAppDTClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MauiAppDTClassLibrary.Migrations.NewMigrations
{
    [DbContext(typeof(ApplicationDbContextIndex))]
    partial class ApplicationDbContextIndexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MauiAppDTClassLibrary.Models.FileManagerModels.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileItemId");

                    b.ToTable("FileItem");
                });

            modelBuilder.Entity("MauiAppDTClassLibrary.Models.FileManagerModels.IndexedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIndexed")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IndexedFiles");
                });

            modelBuilder.Entity("MauiAppDTClassLibrary.Models.FileManagerModels.FileItem", b =>
                {
                    b.HasOne("MauiAppDTClassLibrary.Models.FileManagerModels.FileItem", null)
                        .WithMany("Children")
                        .HasForeignKey("FileItemId");
                });

            modelBuilder.Entity("MauiAppDTClassLibrary.Models.FileManagerModels.FileItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
